### PR TITLE
Update server_software_information.conf

### PR DESCRIPTION
**Pull request by sheo13666**

### CODE REVIEW

**Comment by arthurvr** [comment]
Would fix https://github.com/h5bp/server-configs-apache/issues/54.

Thanks for the PR, @sheo13666! We should probably add some comments on why we add this. See the other inline comments as examples. Also, from the original issue:

> we should also add a comment explaining the better alternatives.

**Comment by arthurvr** [comment]
friendly ping for @sheo13666

**Comment by sheo13666** [comment]
sorry my English is bad for detail comments :disappointed:

**Comment by Philosoft** [comment]
@sheo13666  напиши по-русски тогда, и я переведу в меру сил)

**Comment by alrra** [comment]
> sorry my English is bad for detail comments :disappointed:

@sheo13666 I took care of this addition, as it required more then a few comments. Thanks again for bringing this up!

**Pull request closed without merging**
