### PR TITLE
Server conf files

### LINKED ISSUE #1: Should this repo be .conf files?
This topic has come up in the past numerous times, some references:
- h5bp/html5-boilerplate#169
- h5bp/html5-boilerplate#876
- h5bp/server-configs#59

The use of an optimized`.htaccess` file is a great improvement compared to a standard apache install - but it is really just a stepping-stone solution to configuring apache appropriately.

It's kind of hard to cater for all uses but e.g. potential users of this repo include:
- frontend developers using html5-boilerplate
- users, wanting to optimize their site
- developers using html5-boilerplate as part of their project
- server-savvy users

Right now, the first two groups are catered for pretty well - you can drop in the `.htaccess` file into any project and it just works, and is an improvement. Perhaps they can't modify their apache config files, so it's the only solution that works for them  - though arguably shared hosting is less common than in the past, being replaced by vps servers, reducing the significance/relevance of this point.

The last two groups however are not catered for particularly well, a (general) developer using apache may be aware that they could avoid using `.htaccess` files but, through convenience of using the files provided probably won't. A user familiar with apache either won't use the repo at all (and these are the users who could provide the most benefit in terms of future contributions), or needs to spend some time integrating the provided rules into their existing config files.

Perhaps only the boilerplate repo should have/include the `.htaccess` file (generated by some build script).

One way or another, I feel that users should be guided to _the_ best way to use apache, not stopping just short of the finish line.

Comments?

### LINKED ISSUE #72: Add SSL section
It would be fantastic to have an optimised/secured SSL section:
- disable insecure cyphers
- disable insecure protos
- enable/disable renegotiation

and so on ..

### LINKED ISSUE #139: Block access to all hidden files and directories is not working outside .htaccess
There is a rule in server-configs-apache/src/security/file_access.conf, which tries to prevent access to hidden files/directories:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} "!(^|/)\.well-known/([^./]+./?)+$" [NC]
    RewriteCond %{SCRIPT_FILENAME} -d [OR]
    RewriteCond %{SCRIPT_FILENAME} -f
    RewriteRule "(^|/)\." - [F]
</IfModule>
```

That rule is only working within a .htaccess file, but using .htaccess is really slow. As the [documentation](http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond) mentions, `SCRIPT_FILENAME` has constraints when using in context

> If used in per-server context (i.e., before the request is mapped to the filesystem) SCRIPT_FILENAME and REQUEST_FILENAME cannot contain the full local filesystem path since the path is unknown at this stage of processing.

This makes the rule unusable and "unsafe". The good thing is, that the [documentation](http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond) suggests to solve this problem using a URL-based look-ahead feature:

> In order to obtain the full local filesystem path of the request in per-server context, use an URL-based look-ahead %{LA-U:REQUEST_FILENAME} to determine the final value of REQUEST_FILENAME.

There is another problem to this rule used in a non-htaccess context. Rewrite rules are not inherited per default (see [RewriteOptions](http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriteoptions)). So if someone relies on it as a global security measure, but than adds a `<Directory>` or `<VirtualHost>`, files and directories are not protected. Maybe it makes sense to add an inherit option like `InheritDown` or `InheritDownBefore`. This option got introduces with Apache2 Version 2.4.8.

The new rule could look like this:

```
<IfModule mod_rewrite.c>
	RewriteEngine On
	<IfModule mod_version.c>
		<IfVersion >= 2.4.8>
			RewriteOptions InheritDown
		</IfVersion>
	</IfModule>
	RewriteCond %{REQUEST_URI} "!(^|/)\.well-known/([^./]+./?)+$" [NC]
	RewriteCond %{LA-U:REQUEST_FILENAME} -d [OR]
	RewriteCond %{LA-U:REQUEST_FILENAME} -f
	RewriteRule "(^|/)\." - [F]
</IfModule> 
```

### PR DESCRIPTION
**Pull request by LeoColomb**
Closes #1
Closes #72
Closes #139

To-Do:
- [x] Merge SSL conf #168 
- [x] Add redirection tests
- [x] Add vhosts file examples
- [x] Documentation
- [x] Cleanup (remove redondant parts like #153)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Not sure if I can review this later, but IMO we should release a 3.2.0 from the current changes, assuming we don't have breaking ones merged already.

**Comment by LeoColomb** [comment]
> we should release a 3.2.0

Indeed, see #189.

> Not sure if I can review this later

What do you mean?

**Comment by LeoColomb** [comment]
Updated to reduce future noise: everything required for server config is here (tests/examples/documentation).

#168 has been merged into this PR.

Only one commit alter `.htaccess` content: 88d56f1dc3648810855bed3830c1e73cc4c59aee, moving `PROTO` env variable definition where it's actually used.
Behavior is not altered. 

@XhmikosR Let me now if you can review that one, if so take your time, no stress! 😄

@Malvoz You're welcomed to review too! 🙂

**Comment by LeoColomb** [comment]
Friendly bump 🙂

**Comment by Malvoz** [comment]
Just a quick catch on:

> Later in another PR:
> 
>   Cleanup (remove redondant parts like #153, #185)

Remove #185 from https://github.com/h5bp/server-configs-apache/pull/188#issue-276043105, per https://github.com/h5bp/server-configs-nginx/commit/bc39e4c07d23edfc0acd3c11de88e95af5880eee

**Comment by LeoColomb** [comment]
@XhmikosR Are you available for a review? Thx! 😇

**Comment by XhmikosR** [comment]
Sorry, I don't have a lot of time to spend on this repo. Maybe before proceeding with merging this see if a new release should be made from the changes so far https://github.com/h5bp/server-configs-apache/compare/3.2.1...master

**Comment by LeoColomb** [comment]
No problem, just let me know. 🙂 
We can release a new version before merging, for sure.

**Pull request merged**
