### PR TITLE
Prevent forcing https on local hosts

### PR DESCRIPTION
**Pull request by giovannipds**
Hey.
I don't know what you guys think but, I think it'll never be necessary to have local hosts forcing https, so I've included the same lines contained on `src/rewrites/rewrite_www.conf` to the `src/rewrites/rewrite_http_to_https.conf` file.
I couldn't run the tests here, mainly probably because of the outdated devDependencies, so I've edited manually on the dist file as well.
If you do not agree by any reason, I'd like to explain me why, if possible.
Thank you guys. =)

### CODE REVIEW

**Comment by XhmikosR** [comment]
@LeoColomb: thoughts?

I personally don't think this belongs here since it's for development only.

**Comment by LeoColomb** [comment]
> I personally don't think this belongs here since it's for development only.

That's exactly the words I was looking for, thanks! 😆 
So, yes, agree.

**Comment by giovannipds** [comment]
I'm sorry guys, but I may be not understanding your thoughts. Why denying this? I know it's for development only, but, If I'd like to keep the same `.htaccess` between my environments (not that this is a good practice) the rule without the condition lines I've proposed will force HTTPS even on local development (which I guess it'll never be the case, will it?). If it'll never exist HTTPS on local, it'd be better to have that on the condition... wouldn't it? Am I missing something here? cc @XhmikosR @LeoColomb cheers!

**Comment by LeoColomb** [comment]
> not that this is a good practice

😇

My complete thought is that if you're on dev environment using Apache either you simply disable https redirection, either you create a local certificate. But I may be wrong...
Actually, I'm also wondering about all proxy-like software submitting requests to apache on localhost (Varnish?), should we consider the proxy handles https redirection?

**Comment by giovannipds** [comment]
@LeoColomb I just don't understand why you guys are using a different discernment when [rewrite_www.conf](https://github.com/h5bp/server-configs-apache/blob/master/src/rewrites/rewrite_www.conf) uses the same logic. It's helpful, it's logic and won't bother. 2 lines. But I won't be begging for this. You don't to, that's ok.

I don't know about the proxy-like softwares you've mentioned.

**Pull request closed without merging**
