### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by mattbrundage**
rewrote part of the comment for "X-Powered-By" response header

### CODE REVIEW

**Comment by AD7six** [comment]
Looks fine - you'll need to change [the source file](https://github.com/h5bp/server-configs-apache/blob/master/src/security/x-powered-by.conf) - otherwise, that change will be overwritten the next time there's a release.

**Comment by mattbrundage** [comment]
Done.

**Comment by arthurvr** [comment]
You forgot to edit another file as well. Will update it while merging.

**Comment by arthurvr** [comment]
Thanks!

**Pull request closed without merging**
