### PR TITLE
Serve `.md` and `.markdown` files as `text/markdown`

### PR DESCRIPTION
**Pull request by hatzopoulos**
Per RFC 7763 - https://tools.ietf.org/html/rfc7763

---

Thanks @mathiasbynens!

Close h5bp/server-configs-apache#94

### CODE REVIEW

**Comment by mathiasbynens** [comment]
LGTM.

**Comment by hatzopoulos** [comment]
friendly ping to @alrra

**Comment by XhmikosR** [comment]
My only concern is the 1 month. Do we have any more info about that?

**Comment by QWp6t** [comment]
That's a good point. imo should probably be access plus 0 seconds, same as html.

**Comment by XhmikosR** [comment]
I'll merge this manually tomorrow in the dev branch after I make the change in the expires date.

**Comment by XhmikosR** [comment]
Thanks, merged to dev branch.

**Comment by XhmikosR** [comment]
Does anybody know why this breaks tests on dev branch?

**Pull request closed without merging**
