### PR TITLE
Add JPEG XL `image/jxl` MIME type

### PR DESCRIPTION
**Pull request by mathiasbynens**
https://twitter.com/jonsneyers/status/1343241690203746310

### CODE REVIEW

**Comment by LeoColomb** [comment]
Thanks for opening this PR @mathiasbynens! 

Do you have any links or references about specification, usage recommendation and browser support?

**Comment by Malvoz** [comment]
Explainer: http://sneyers.info/jxl/
Official site: https://jpeg.org/jpegxl/
TBD support data: https://github.com/Fyrd/caniuse/issues/5041

FWIW there are at least 2 other JPEG formats, however it doesn't look like they've gotten much attention from implementers: [JPEG 2000](https://caniuse.com/jpeg2000) (only supported in Safari) and [JPEG XR](https://caniuse.com/jpegxr) (only supported in IE). I suppose JPEG XL intends to supersede those formats.

**Comment by mathiasbynens** [comment]
Chromium tracking issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1109698

**Comment by LeoColomb** [comment]
https://caniuse.com/jpegxl

**Review by LeoColomb — APPROVED** [review]

**Pull request merged**
