### PR TITLE
Setting headers based on content-type

### LINKED ISSUE #163: Setting headers based on content-type
Your documentation states "mod_headers cannot match based on the content-type", but the following works for me using Apache 2.4.35:

```apacheconf
Header set Referrer-Policy "no-referrer-when-downgrade" "expr=%{CONTENT_TYPE} =~ m#text/html#"
Header set X-Frame-Options "DENY" "expr=%{CONTENT_TYPE} =~ m#text/html#"
Header set X-UA-Compatible "IE=edge" "expr=%{CONTENT_TYPE} =~ m#text/html#"
Header set X-XSS-Protection "1; mode=block" "expr=%{CONTENT_TYPE} =~ m#text/html#"
```

Is there another reason to specifically unset headers?

### PR DESCRIPTION
**Pull request by LeoColomb**
Setting headers based on content-type instead of `FilesMatch` conditions.

~~WIP: need performance tests~~

fix #163

### CODE REVIEW

**Comment by XhmikosR** [comment]
Love this, assuming tests pass :)

**Comment by LeoColomb** [comment]
> assuming tests pass

Yes, I really don't know why there are some errors with only one request ([always the same, `test-schema.json`](https://travis-ci.org/h5bp/server-configs-apache/jobs/458963362#L1834)).

And don't have any idea how to fix it...

**Comment by XhmikosR** [comment]
Indeed, very weird. For some reason this file can't be served right. Is the MIME type matching with what we expect? Just thinking out loud.

**Comment by XhmikosR** [comment]
Or another thing I notice is that `test-schema.json` is the only file with a slash in the filename. Maye there's a regex somewhere or something that fails there.

**Comment by LeoColomb** [comment]
Well, I just found that https://github.com/h5bp/server-configs-apache/commit/54477eb3b05b2ac6ab284708db3430623dafd451 adds the following exception:

https://github.com/h5bp/server-configs-apache/blob/57f6c120a2936eb6434fa953694e83d8847ee74c/bin/setup_configs/2.4.conf#L15-L17

**Comment by LeoColomb** [comment]
Just added a test to check with the other file with custom type defined in VirtualHost conf file.

https://github.com/h5bp/server-configs-apache/blob/57f6c120a2936eb6434fa953694e83d8847ee74c/bin/setup_configs/2.4.conf#L11-L17

[Same error](https://travis-ci.org/h5bp/server-configs-apache/jobs/459213033#L1893-L1936). I suspect a mismatch with the expression evaluation delay (but why?!).

**Comment by XhmikosR** [comment]
I don't think `/.well-known/manifest.json` is supposed to be accessible.

**Comment by LeoColomb** [comment]
This file should be accessible. But even not accessible, the server must not answer a 500.

**Comment by LeoColomb** [comment]
Fixed. Was a config mismatch indeed.
Fully tested with attached CI of course but also rigorously on a local instance, with some special cases (vhosts, redefining types, etc.), everything is fine.

**Comment by LeoColomb** [comment]
Oh and the benchmark on the CI show a "impact" of ~2ms/req on a set of ~18k requests, not sufficient enough to make this change take the blame.

```diff
-    http_req_waiting...........: avg=66.07ms  min=1.08ms  med=24.42ms max=1.03s   p(90)=175.9ms  p(95)=223.98ms
+    http_req_waiting...........: avg=68.26ms  min=1.04ms med=23.62ms max=692.59ms p(90)=191.31ms p(95)=234.89ms
-    http_reqs..................: 18645   932.246028/s
+    http_reqs..................: 18105   905.245938/s
```

Looks safe to me.

**Comment by XhmikosR** [comment]
We can't trust any data on CI unless we do multiple runs and get the average. Can you quickly add a temp patch to run the benchmark tests, say 5 times? If all is good you rebase and drop that patch before the merge.

**Comment by LeoColomb** [comment]
Sure, we can trigger a build even without a push.

**Comment by XhmikosR** [comment]
BTW, I also think this is a pretty cool change, dropping a lot of stuff. The non-whitespace diff shows the real picture https://github.com/h5bp/server-configs-apache/pull/166/files?utf8=%E2%9C%93&diff=unified&w=1

Also, I doubt this has a significant effect on the speed, but I just want to be sure before merging this.

**Comment by XhmikosR** [comment]
>Sure, we can trigger a build even without a push.

That's not the same though. The tests should run 5x on the same build.

**Comment by LeoColomb** [comment]
Oh, OK, I see.
It's possible too.

**Comment by LeoColomb** [comment]
<details>
<summary>Before</summary>


```
$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 18779 ✗ 0    
    data_received..............: 19 MB   955 kB/s
    data_sent..................: 1.7 MB  86 kB/s
    http_req_blocked...........: avg=6.77µs   min=1.33µs  med=2.2µs   max=1.59ms   p(90)=2.62µs   p(95)=3µs     
    http_req_connecting........: avg=2.02µs   min=0s      med=0s      max=1.5ms    p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=66.27ms  min=1.47ms  med=31.92ms max=453.06ms p(90)=181.23ms p(95)=212.31ms
    http_req_receiving.........: avg=39.28µs  min=17.62µs med=33.77µs max=8.52ms   p(90)=47.24µs  p(95)=52.43µs 
    http_req_sending...........: avg=273.24µs min=7.54µs  med=12.8µs  max=130.01ms p(90)=22.64µs  p(95)=27.96µs 
    http_req_tls_handshaking...: avg=0s       min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=65.96ms  min=1.42ms  med=31.43ms max=452.99ms p(90)=180.8ms  p(95)=211.89ms
    http_reqs..................: 18779   938.883895/s
    iteration_duration.........: avg=66.42ms  min=1.6ms   med=32.08ms max=453.2ms  p(90)=181.39ms p(95)=212.52ms
    iterations.................: 18779   938.883895/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
27.87s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100

    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 18602 ✗ 0    
    data_received..............: 19 MB   946 kB/s
    data_sent..................: 1.7 MB  86 kB/s
    http_req_blocked...........: avg=6.97µs   min=1.27µs med=2.22µs  max=3.73ms   p(90)=2.66µs   p(95)=2.99µs  
    http_req_connecting........: avg=1.9µs    min=0s     med=0s      max=2.05ms   p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=66.94ms  min=1.19ms med=50.22ms max=512.22ms p(90)=162.2ms  p(95)=193.27ms
    http_req_receiving.........: avg=39.5µs   min=18.5µs med=33.5µs  max=16.6ms   p(90)=49.23µs  p(95)=55.42µs 
    http_req_sending...........: avg=277.73µs min=7.92µs med=13.1µs  max=274.58ms p(90)=23.99µs  p(95)=30.81µs 
    http_req_tls_handshaking...: avg=0s       min=0s     med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=66.62ms  min=1.14ms med=49.81ms max=512.18ms p(90)=161.56ms p(95)=192.23ms
    http_reqs..................: 18602   929.818147/s
    iteration_duration.........: avg=67.09ms  min=1.35ms med=50.36ms max=512.38ms p(90)=162.34ms p(95)=193.39ms
    iterations.................: 18602   929.818147/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
27.95s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 18727 ✗ 0    
    data_received..............: 19 MB   952 kB/s
    data_sent..................: 1.7 MB  86 kB/s
    http_req_blocked...........: avg=7.66µs   min=1.26µs  med=2.19µs  max=4.09ms   p(90)=2.75µs   p(95)=4.04µs  
    http_req_connecting........: avg=2µs      min=0s      med=0s      max=3.82ms   p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=66.13ms  min=1.13ms  med=16.38ms max=985.45ms p(90)=181.38ms p(95)=231.53ms
    http_req_receiving.........: avg=43.62µs  min=18.09µs med=34.87µs max=16.75ms  p(90)=51.34µs  p(95)=56.44µs 
    http_req_sending...........: avg=396.83µs min=7.57µs  med=12.88µs max=443.82ms p(90)=25.96µs  p(95)=30.31µs 
    http_req_tls_handshaking...: avg=0s       min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=65.69ms  min=1.08ms  med=15.85ms max=985.41ms p(90)=180.6ms  p(95)=230.65ms
    http_reqs..................: 18728   936.386398/s
    iteration_duration.........: avg=66.29ms  min=1.23ms  med=16.52ms max=985.6ms  p(90)=181.54ms p(95)=231.67ms
    iterations.................: 18727   936.336398/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
27.69s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 18847 ✗ 0    
    data_received..............: 19 MB   958 kB/s
    data_sent..................: 1.7 MB  87 kB/s
    http_req_blocked...........: avg=9.28µs   min=1.32µs  med=2.17µs  max=13.22ms  p(90)=2.63µs   p(95)=3.31µs  
    http_req_connecting........: avg=3.23µs   min=0s      med=0s      max=13.14ms  p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=65.98ms  min=1.13ms  med=21.18ms max=880.85ms p(90)=179.68ms p(95)=222.34ms
    http_req_receiving.........: avg=42.18µs  min=17.91µs med=37.19µs max=21.02ms  p(90)=49.58µs  p(95)=55.03µs 
    http_req_sending...........: avg=344.27µs min=7.77µs  med=12.66µs max=228.46ms p(90)=22.79µs  p(95)=28.25µs 
    http_req_tls_handshaking...: avg=0s       min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=65.59ms  min=1.08ms  med=20.65ms max=880.81ms p(90)=178.7ms  p(95)=221.55ms
    http_reqs..................: 18847   942.345434/s
    iteration_duration.........: avg=66.12ms  min=1.23ms  med=21.34ms max=881.02ms p(90)=179.87ms p(95)=222.48ms
    iterations.................: 18847   942.345434/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
27.93s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 18783 ✗ 0    
    data_received..............: 19 MB   955 kB/s
    data_sent..................: 1.7 MB  86 kB/s
    http_req_blocked...........: avg=7.46µs   min=1.24µs med=2.2µs   max=8.1ms    p(90)=2.75µs   p(95)=4.22µs  
    http_req_connecting........: avg=2.6µs    min=0s     med=0s      max=8.02ms   p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=65.93ms  min=1.12ms med=29.43ms max=647.65ms p(90)=174.29ms p(95)=213.46ms
    http_req_receiving.........: avg=42.48µs  min=17.6µs med=34.56µs max=16.52ms  p(90)=49.43µs  p(95)=54.98µs 
    http_req_sending...........: avg=239.78µs min=8.08µs med=12.84µs max=227.44ms p(90)=25.88µs  p(95)=32.1µs  
    http_req_tls_handshaking...: avg=0s       min=0s     med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=65.65ms  min=1.07ms med=29.01ms max=647.6ms  p(90)=173.94ms p(95)=213.01ms
    http_reqs..................: 18783   939.146268/s
    iteration_duration.........: avg=66.09ms  min=1.22ms med=29.65ms max=647.77ms p(90)=174.41ms p(95)=213.59ms
    iterations.................: 18783   939.146268/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
```
</details>

<details>
<summary>After</summary>


```
28.16s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 20110 ✗ 0    
    data_received..............: 20 MB   1.0 MB/s
    data_sent..................: 1.9 MB  92 kB/s
    http_req_blocked...........: avg=12.22µs  min=1.33µs  med=2.29µs  max=61.2ms   p(90)=2.85µs   p(95)=3.85µs  
    http_req_connecting........: avg=6.34µs   min=0s      med=0s      max=57.45ms  p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=61.54ms  min=1.05ms  med=26.38ms max=688.06ms p(90)=165.05ms p(95)=212.73ms
    http_req_receiving.........: avg=45.65µs  min=15.37µs med=35.22µs max=12.05ms  p(90)=51.22µs  p(95)=56.43µs 
    http_req_sending...........: avg=294.87µs min=7.35µs  med=13.44µs max=287.91ms p(90)=26.86µs  p(95)=32.6µs  
    http_req_tls_handshaking...: avg=0s       min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=61.2ms   min=1ms     med=26.07ms max=688.02ms p(90)=164.44ms p(95)=211.55ms
    http_reqs..................: 20110   1005.495847/s
    iteration_duration.........: avg=61.71ms  min=1.17ms  med=26.52ms max=688.23ms p(90)=165.25ms p(95)=212.92ms
    iterations.................: 20110   1005.495847/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
28.28s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 19781 ✗ 0    
    data_received..............: 20 MB   1.0 MB/s
    data_sent..................: 1.8 MB  91 kB/s
    http_req_blocked...........: avg=7.22µs   min=1.16µs  med=2.31µs  max=4.29ms   p(90)=2.92µs   p(95)=4.31µs  
    http_req_connecting........: avg=2.12µs   min=0s      med=0s      max=4.2ms    p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=62.74ms  min=1.04ms  med=21.27ms max=582.46ms p(90)=170.13ms p(95)=201.58ms
    http_req_receiving.........: avg=45.13µs  min=17.55µs med=36.8µs  max=20.92ms  p(90)=54.31µs  p(95)=62.69µs 
    http_req_sending...........: avg=199.72µs min=7.63µs  med=13.68µs max=128.01ms p(90)=27.53µs  p(95)=35.09µs 
    http_req_tls_handshaking...: avg=0s       min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=62.49ms  min=1ms     med=20.6ms  max=582.41ms p(90)=169.79ms p(95)=201.3ms 
    http_reqs..................: 19781   989.038077/s
    iteration_duration.........: avg=62.9ms   min=1.19ms  med=21.43ms max=582.59ms p(90)=170.28ms p(95)=201.72ms
    iterations.................: 19781   989.038077/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
28.06s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 20244 ✗ 0    
    data_received..............: 21 MB   1.0 MB/s
    data_sent..................: 1.9 MB  93 kB/s
    http_req_blocked...........: avg=7.03µs   min=1.31µs   med=2.28µs  max=2.89ms   p(90)=2.84µs   p(95)=4.37µs  
    http_req_connecting........: avg=2.08µs   min=0s       med=0s      max=1.69ms   p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=61.38ms  min=1.02ms   med=15.24ms max=545.28ms p(90)=170.34ms p(95)=212.65ms
    http_req_receiving.........: avg=43.84µs  min=15.28µs  med=35.73µs max=12.3ms   p(90)=52.9µs   p(95)=57.8µs  
    http_req_sending...........: avg=214.79µs min=7.79µs   med=13.38µs max=224.76ms p(90)=26.68µs  p(95)=31.74µs 
    http_req_tls_handshaking...: avg=0s       min=0s       med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=61.12ms  min=979.71µs med=14.7ms  max=545.23ms p(90)=170.14ms p(95)=212.44ms
    http_reqs..................: 20244   1012.195624/s
    iteration_duration.........: avg=61.54ms  min=1.14ms   med=15.44ms max=545.43ms p(90)=170.47ms p(95)=212.81ms
    iterations.................: 20244   1012.195624/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
27.96s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
time="2019-03-13T10:45:11Z" level=info msg=Running i=955 t=944.078096ms
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 20205 ✗ 0    
    data_received..............: 21 MB   1.0 MB/s
    data_sent..................: 1.9 MB  93 kB/s
    http_req_blocked...........: avg=6.36µs  min=1.29µs   med=2.3µs   max=1.66ms   p(90)=2.8µs    p(95)=3.63µs  
    http_req_connecting........: avg=1.64µs  min=0s       med=0s      max=795.56µs p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=61.52ms min=1.03ms   med=40.51ms max=661.46ms p(90)=148.61ms p(95)=179.44ms
    http_req_receiving.........: avg=38.78µs min=18.99µs  med=34.35µs max=6.01ms   p(90)=47.71µs  p(95)=53.92µs 
    http_req_sending...........: avg=202.6µs min=8.62µs   med=13.41µs max=433.37ms p(90)=24.78µs  p(95)=30.19µs 
    http_req_tls_handshaking...: avg=0s      min=0s       med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=61.28ms min=990.17µs med=40.1ms  max=661.38ms p(90)=148.23ms p(95)=179.02ms
    http_reqs..................: 20205   1010.246451/s
    iteration_duration.........: avg=61.67ms min=1.14ms   med=40.64ms max=661.61ms p(90)=148.76ms p(95)=179.57ms
    iterations.................: 20205   1010.246451/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
27.83s$ ./test/bin/k6 run test/lib/benchmark.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io
  execution: local
     output: -
     script: test/lib/benchmark.js
    duration: -, iterations: -
         vus: 1, max: 100
    ✓ is status 200
  ✓ checks.....................: 100.00% ✓ 20380 ✗ 0    
    data_received..............: 21 MB   1.0 MB/s
    data_sent..................: 1.9 MB  94 kB/s
    http_req_blocked...........: avg=8.2µs   min=1.29µs   med=2.28µs  max=7.6ms    p(90)=2.78µs   p(95)=3.7µs   
    http_req_connecting........: avg=2.57µs  min=0s       med=0s      max=7.46ms   p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=60.97ms min=1.03ms   med=32.56ms max=1s       p(90)=149.28ms p(95)=190.69ms
    http_req_receiving.........: avg=38.49µs min=17.79µs  med=34.36µs max=10.31ms  p(90)=47.35µs  p(95)=52.71µs 
    http_req_sending...........: avg=316.4µs min=8.06µs   med=13.29µs max=268.26ms p(90)=24.67µs  p(95)=29.98µs 
    http_req_tls_handshaking...: avg=0s      min=0s       med=0s      max=0s       p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=60.62ms min=988.36µs med=31.96ms max=1s       p(90)=148.82ms p(95)=189.61ms
    http_reqs..................: 20380   1018.99514/s
    iteration_duration.........: avg=61.12ms min=1.15ms   med=32.7ms  max=1s       p(90)=149.42ms p(95)=190.84ms
    iterations.................: 20380   1018.99514/s
    vus........................: 1       min=1   max=100
    vus_max....................: 100     min=100 max=100
The command "./test/bin/k6 run test/lib/benchmark.js" exited with 0.
```
</details>

**Pull request merged**
