### PR TITLE
Correct mime-types for atom, rdf, and rss

### PR DESCRIPTION
**Pull request by gennadiylitvinyuk**
This solves some issues with nosniff header also.

atom: application/atom+xml  (https://www.iana.org/assignments/media-types/media-types.xhtml)
rdf:    application/rdf+xml (http://www.w3.org/2008/01/rdf-media-types)
rss:   application/rss+xml (http://www.rssboard.org/rss-mime-type-application.txt)

### CODE REVIEW

**Comment by AD7six** [comment]
Seems appropriate - but I can't merge it with failing tests =).

**Comment by gennadiylitvinyuk** [comment]
@AD7six Found some time to fix tests.

**Comment by alrra** [comment]
@gennadiylitvinyuk, @AD7six  See: https://github.com/h5bp/html5-boilerplate/issues/989.

**Comment by alrra** [comment]
@gennadiylitvinyuk Thanks for the pull request, however, the media types were intentionally set to `application/xml`, see h5bp/html5-boilerplate#989.

**Comment by gennadiylitvinyuk** [comment]
Hi @alrra,

I am a witness to a opposite function, compared to the described in h5bp/html5-boilerplate#989.

With `nosniff` header set, IE does not try to interpret `application/xml` as rss/atom/..., but downloads it directly. It is a sense of the `nosniff`-header.

So we should either set the nosniff-header and define mime-types correctly, or don't set it, and let browsers interpret it from `application/xml`, but not both in the same time.

**Comment by alrra** [comment]
@gennadiylitvinyuk Sorry for the delay on this.

--

> With nosniff header set, IE does not try to interpret application/xml as rss/atom/..., but downloads it directly. It is a sense of the nosniff-header.

@gennadiylitvinyuk I could not reproduce that. The files where display [as intended](https://github.com/h5bp/html5-boilerplate/issues/989) in all versions of Internet Explorer. 

| Browser (OS) | `.atom` | `.rdf` | `.rss` |
|:---:|:---:|:---:|:---:|
| IE 6 <br>(WIndows XP) |  |   |   |
| IE 7 <br>(WIndows XP) |  |   |   |
| IE 8 <br>(WIndows XP) |  |   |   |
| IE 9 <br>(WIndows 7) |  |   |   |
| IE 10 <br>(WIndows 7) |  |   |   |
| IE 11 <br>(WIndows 7) |  |   |   |

**Comment by gennadiylitvinyuk** [comment]
Hi @alrra 

You has obviously shown the *unintended behavior*.

The IE will *download* any resource, if it does not know how to process it, and `nosniff` is set.

Please see: http://blogs.msdn.com/b/ie/archive/2008/07/02/ie8-security-part-v-comprehensive-protection.aspx

If you set plain/text with nosniff to a html file, you will see/download source code of the file (since IE8) but you will not get it interpreted as a HTML. The same is with images served as binary...

The changes were intended to let IE interpret file types it could, and show them correctly with provided processors, for example interpret rss/atom feed and show them correctly (see IE7 screenshots, it simply ignores nosniff,  ie8+ does not interpret them anymore)

**Comment by mathiasbynens** [comment]
@gennadiylitvinyuk I don’t understand what you’re getting at. @alrra’s screenshots show that IE knows how to process the files with the current MIME types. Why would displaying the feed in the browser be the unintended behavior?

**Comment by hatzopoulos** [comment]
@mathiasbynens 

From the looks of it, I believe what @gennadiylitvinyuk means is that when IE loads an RSS feed it tries to sniff the content so it's RSS previewer kicks in and `nosniff` included in the header will cause IE to simply show the 'unstyled' raw feed rather then the Microsoft Preview. Which one might consider a bad user experience. 

The tests from https://github.com/h5bp/html5-boilerplate/issues/989 were not done in Windows as the tester did not have them on hand at the time but @alrra has done them now with the nosniff header in place. And IE7 ignores wrongly ignores the header and parses the page in it's native RSS viewer.

For example IE11 loads an RSS feed like https://developer.apple.com/news/rss/news.rss and renders it something like below but with the nosniff header IE just displays the raw source. FWIW apple.com was sending `Content-Type:application/rss+xml; charset=UTF-8` without nosniff in the screenshot below.

image

**Comment by alrra** [comment]
@hatzopoulos Thank you for your comment!

> The IE will download any resource...

@gennadiylitvinyuk In the future please try to be [more clear](https://github.com/h5bp/server-configs-apache/blob/master/CONTRIBUTING.md#bug-reports) (e.g.: I also interpreted "IE will download" as IE will try to download a file by [showing a prompt to the user](https://cloud.githubusercontent.com/assets/1223565/6425851/d2fc706a-bf46-11e4-97e1-ec998e33b8b3.png)).

--

I did some more tests (see below), and it seems that it's ok to change the media types for `.atom` and `.rss`, but not for `.rdf`.

Note: After this change, the only minor issue will be that IE 6 users will get the download prompt for `.atom` and `.rss` files, but that [isn't really a big problem nowadays](https://github.com/h5bp/server-configs-apache#support).

**Comment by alrra** [comment]
* `.atom`, `.rdf` and `.rss` served with their appropriate media types

  | Browser (OS) | `.atom` | `.rdf` | `.rss` |
|:---:|:---:|:---:|:---:|
| Chrome 40<br>(OS X 10.10.2) |  |  |  |
| Chrome 40 (Android 4.3.0) |  |  |  |
| Firefox 36<br>(OS X 10.10.2) |  |  |  |
| IE 6<br>(Windows XP) |  |  |  |
| IE 7<br>(Windows XP) |  |  |  |
| IE 8<br>(Windows XP) |  |  |  |
| IE 9<br>(Windows 7) |  |  |  |
| IE 10<br>(Windows 7) |  |  |  |
| IE 11<br>(Windows 7) |  |  |  |
| Safari 8.0.3<br>(OS X 10.10.2) |  |  |  |
| Safari<br>(iOS 8.1.3) |  |  |  |


* `.atom`, `.rdf` and `.rss` served with their appropriate media types + `X-Content-Type-Options: "nosniff"` header

  | Browser (OS) | `.atom` | `.rdf` | `.rss` |
|:---:|:---:|:---:|:---:|
| Chrome 40<br>(OS X 10.10.2) |  |  |  |
| Chrome 40 (Android 4.3.0) |  |  |  |
| Firefox 36<br>(OS X 10.10.2) |  |  |  |
| IE 6<br>(Windows XP) |  |  |  |
| IE 7<br>(Windows XP) |  |  |  |
| IE 8<br>(Windows XP) |  |  |  |
| IE 9<br>(Windows 7) |  |  |  |
| IE 10<br>(Windows 7) |  |  |  |
| IE 11<br>(Windows 7) |  |  |  |
| Safari 8.0.3<br>(OS X 10.10.2) |  |  |  |
| Safari<br>(iOS 8.1.3) |  |  |  |


* `.atom`, `.rdf` and `.rss` served with the `application/xml` media type

  | Browser (OS) | `.atom` | `.rdf` | `.rss` |
|:---:|:---:|:---:|:---:|
| Chrome 40<br>(OS X 10.10.2) |  |  |  |
| Chrome 40 (Android 4.3.0) |  |  |  |
| Firefox 36<br>(OS X 10.10.2) |  |  |  |
| IE 6<br>(Windows XP) |  |  |  |
| IE 7<br>(Windows XP) |  |  |  |
| IE 8<br>(Windows XP) |  |  |  |
| IE 9<br>(Windows 7) |  |  |  |
| IE 10<br>(Windows 7) |  |  |  |
| IE 11<br>(Windows 7) |  |  |  |
| Safari 8.0.3<br>(OS X 10.10.2) |  |  |  |
| Safari<br>(iOS 8.1.3) |  |  |  |


* `.atom`, `.rdf` and `.rss` served with the `application/xml` media type + `X-Content-Type-Options: "nosniff"` header

  | Browser (OS) | `.atom` | `.rdf` | `.rss` |
|:---:|:---:|:---:|:---:|
| Chrome 40<br>(OS X 10.10.2) |  |  |  |
| Chrome 40 (Android 4.3.0) |  |  |  |
| Firefox 36<br>(OS X 10.10.2) |  |  |  |
| IE 6<br>(Windows XP) |  |  |  |
| IE 7<br>(Windows XP) |  |  |  |
| IE 8<br>(Windows XP) |  |  |  |
| IE 9<br>(Windows 7) |  |  |  |
| IE 10<br>(Windows 7) |  |  |  |
| IE 11<br>(Windows 7) |  |  |  |
| Safari 8.0.3<br>(OS X 10.10.2) |  |  |  |
| Safari<br>(iOS 8.1.3) |  |  |  |

--

Notes:

 * Opera behaved exactly like Chrome
 * The default Browser for Android 4.3.0 (Samsung Galaxy S3) behaved the same for all cases:
   <p></p>

**Pull request closed without merging**
