### PR TITLE
Font MIME types following RFC 8081

### PR DESCRIPTION
**Pull request by LeoColomb**
Recent changes introduced by the [RFC 8081](https://tools.ietf.org/html/rfc8081) and [registered at IANA](https://www.iana.org/assignments/media-types/media-types.xml#font).

Current|New
---|---
`application/x-font-ttf`|`font/ttf`
`font/opentype`|`font/otf`
`application/font-woff`|`font/woff`
`application/font-woff2`|`font/woff2`
`application/x-font-ttf` (ttc)|`font/collection`

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Which browsers support these MIME types?

**Comment by LeoColomb** [comment]
At least the latest version of modern browsers, but this is hard to say except not being able to produce an error.
That said, browsers [usually](https://mimesniff.spec.whatwg.org/#matching-a-font-type-pattern) ignore the font media types and simply sniff the bytes to figure out the font type.

Also, as an example, Google Fonts already use these "new" types:

```
$ curl -I https://fonts.gstatic.com/s/lato/v13/9k-RPmcnxYEPm8CNFsH2gg.woff

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: font/woff
[...]
```
_Extracted from [Lato](https://fonts.googleapis.com/css?family=Lato) served for IE_

```
$ curl -I https://fonts.gstatic.com/s/lato/v13/UyBMtLsHKBKXelqf4x7VRQ.woff2

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: font/woff2
[...]
```
_Extracted from [Lato](https://fonts.googleapis.com/css?family=Lato) served for Chrome_

**Comment by mathiasbynens** [comment]
https://github.com/jshttp/mime-db/issues/77

**Comment by LeoColomb** [comment]
This is a very good link, thanks!

But this seems to be kind a vicious circle: if everyone wait to the other be updated, no one will do.
Most of the time it can be understandable to avoid errors and breaking things, but in our case the worst thing this change could raise is a notice in some old browsers. 🤔 

Isn't it? What is your opinion?
🙂

**Comment by mathiasbynens** [comment]
Yeah, I agree this should be merged! Could you please take a look at the CI failure?

**Comment by mathiasbynens** [comment]
Any reason why `font/sfnt` is not added?

**Comment by LeoColomb** [comment]
Rebased.

**Comment by mathiasbynens** [comment]
👍

**Comment by XhmikosR** [comment]
@LeoColomb: Shouldn't we remove the old types completely?

**Comment by LeoColomb** [comment]
I would keep them for compatibility as software may force them. 
But that said, I don't know at all.

**Pull request merged**
