### PR TITLE
Fix typo in .htaccess

### PR DESCRIPTION
**Pull request by hnarayanan**
This fixes a tiny typo reported [here](https://github.com/h5bp/html5-boilerplate/issues/1707).

### CODE REVIEW

**Comment by arthurvr** [comment]
This needs to be edited in the actual source file as well, [here](https://github.com/h5bp/server-configs-apache/blob/e603554f559b1be4861553239e22a7844075bedc/src/media_types/media_types.conf#L50).

**Comment by arthurvr** [comment]
Thanks for submitting a pull request!

**Comment by hnarayanan** [comment]
I've updated the patch!

**Comment by arthurvr** [comment]
Thanks!

**Pull request closed without merging**
